### ISSUE TITLE
Panic: "no specification for type"

### ISSUE THREAD

**Issue by caseybarker** [Antonboom/errname#24]
I'm running `errname` via `golangci-lint` v1.54.0, and I see this panic when run against a particular source file:

```
ERRO [runner] Panic: errname: package "defserve" (isInitialPkg: true, needAnalyzeSource: true): no specification for type : goroutine 6033 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:109 +0x27c
panic({0xf59020?, 0xc002762070?})
        runtime/panic.go:914 +0x21f
github.com/Antonboom/errname/pkg/analyzer.run.func3({0x1366bf0?, 0xc003836ae0?})
        github.com/Antonboom/errname@v0.1.10/pkg/analyzer/analyzer.go:65 +0x165
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc004f54720, {0x1ad6310?, 0x1?, 0xc00558cb58?}, 0xc00558cc18)
        golang.org/x/tools@v0.12.0/go/ast/inspector/inspector.go:82 +0x9a
github.com/Antonboom/errname/pkg/analyzer.run(0xc0042240d0)
        github.com/Antonboom/errname@v0.1.10/pkg/analyzer/analyzer.go:55 +0x1f7
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc00531e8a0)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:195 +0x9d6
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:113 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0018a0410, {0x10f91df, 0x7}, 0xc0021a8748)
        github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc001737c80?)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:112 +0x7a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc00531e8a0)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa8
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 357
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x205 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: errname: package "defserve" (isInitialPkg: true, needAnalyzeSource: true): no specification for type  
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: errname: package "defserve" (isInitialPkg: true, needAnalyzeSource: true): no specification for type 
```

I can't post the entire source file, but I'm guessing the offending bit is this:

```
type (
	Req  any
	Resp any
)

type timeoutError[REQ Req, RESP Resp] struct {
	sending bool
	err     error
}
```

**Comment by Antonboom** [comment]
@caseybarker, hello! Thank u for request.

Please provide 

1. `timeoutError.Error()` method signature (or full implementation of type, would be great).
2. Why there is no fields with types `REQ`/`RESP` into struct? How it used?

🙏

**Comment by caseybarker** [comment]
Thanks for looking at this! Here are the methods on that type:

```
func (e *timeoutError[REQ, RESP]) Error() string {
	var req REQ

	var resp RESP

	direction := "sending"
	if !e.sending {
		direction = "receiving"
	}

	return fmt.Sprintf("deferred call %T->%T timeout %s: %s",
		reflect.TypeOf(req), reflect.TypeOf(resp), direction, e.err.Error())
}

func (e *timeoutError[REQ, RESP]) Unwrap() error {
	return e.err
}
```

This package is a wrapper for gRPC calls, so it accepts arbitrary request/response types, which are just gRPC message structures. The error has the types so it can include them in the error string.

**Comment by Antonboom** [comment]
Thank!

Fixed by https://github.com/Antonboom/errname/pull/25, please waiting for new release of `golangci-lint`

Also I improved an error message, now
```go
panic: unsupported Error() receiver type "timeoutError[REQ, RESP]"
```

**Comment by Antonboom** [comment]
Thank!

Fixed by https://github.com/Antonboom/errname/pull/25, please waiting for new release of `golangci-lint`

Also I improved an error message, now
```go
panic: unsupported Error() receiver type "timeoutError[REQ, RESP]"
```
